### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by cmahnke** [4creators/jxrlib#9]
After updating Alpine from 3.20 to 3.21 compilation fails with this message:
```
120.3 /tmp/build/jxrlib/jxrgluelib/JXRGlueJxr.c: In function 'CalcMetadataSizeLPWSTR':
120.3 /tmp/build/jxrlib/jxrgluelib/JXRGlueJxr.c:66:48: error: implicit declaration of function 'wcslen' [-Wimplicit-function-declaration]
120.3    66 |         U32 uiCBWithNull = sizeof(U16) * ((U32)wcslen((wchar_t *) var.VT.pwszVal) + 1); // +1 for NULL term;
120.3       |                                                ^~~~~~
120.3 make: *** [Makefile:140: /tmp/build/jxrlib/build/jxrgluelib/JXRGlueJxr.o] Error 1
```
Is it save to disable `-Wimplicit-function-declaration`?
